config/routes.rb
Atndr::Application.routes.draw do
  resources :cities

  get "getsongs/index"

  get "map/index"

  get "admin/index"
  get "admin/getshows"
  get "admin/geocodeall"
  
  get "filters/index"
  
  get "events/truncate"

  resources :events

  root :to => 'app#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	serialize :songs

  geocoded_by :location
  after_validation :geocode
  acts_as_gmappable


	def gmaps4rails_address
	#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
	  "#{self.location}" 
	end

  def gmaps4rails_sidebar
    listing =""
  	b = self.bands.split('|')
  	band = ''
  	#remove the first elements and call it headliner
  	headliner = b.shift()	
  	if b.length < 4
  		band = b.join(',').to_s
  	else
  		band = b[0..2].join(',').to_s
  		l=(b.length-3).to_s
  		band << ', '+l+' more...'  	end
  	
		listing += "<div class='"
    #if has songs, show headphones class
		if self.songs.length > 0
		  listing += " hassongs"
	  end
	  if b.length == 0
  		listing += " singleact" 
  	end
    listing += " listing'><span class='headliner'>#{headliner}</span>"
    #if has supporting acts, list them
    if b.length > 0
  		listing += "<p class='acts'>#{band}</p>" 
  	end
  	return listing
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.find(:all, :order =>'time ASC')
	@length = @events.length
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end
  
  def truncate
  	Event.destroy_all()
  	redirect_to events_url, :notice => "Events Deleted"
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bands %><br />
    <%= f.text_area :bands %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_area :time %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% if flash[:error] -%>
  <p class='error'><%=h flash[:error] %></p>
<% end -%>
<% if flash[:notice] -%>
  <p class='notice'><%=h flash[:notice] %></p>
<% end -%>

<h1>Listing events</h1>
<br />
<strong><%= @length %> events</strong>
<%= link_to "Delete All Events", events_truncate_path, :class => 'button', :confirm => 'Please be sure, this will delete all events' %>
<br />
<table>
  <tr>
    <th>Bands</th>
    <th>Time</th>
    <th>Location</th>
    <th>Venue</th>
    <th>Latitude</th>
    <th>Longitude</th>
	<th>StartTime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.bands %></td>
    <td><%= event.time %></td>
    <td><%= event.location %></td>
    <td><%= event.venue %></td>
    <td><%= event.latitude %></td>
    <td><%= event.longitude %></td>
    <td><%= event.starttime %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path, :class => 'button' %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bands:</b>
  <%= @event.bands %>
</p>

<p>
  <b>Time:</b>
  <%= @event.time %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location %>
</p>

<p>
  <b>Latitude:</b>
  <%= @event.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @event.longitude %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>